---
- name: Test WinRM Connectivity
  hosts: all
  gather_facts: no

  tasks:

    - name: Test connectivity using win_ping
      ansible.windows.win_ping:

    - name: Check hostname
      ansible.windows.win_shell: hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout

    - name: Check logged in user
      ansible.windows.win_shell: whoami
      register: user_output

    - name: Display logged in user
      debug:
        var: user_output.stdout
